version: '3.9'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

